services:
  # Servicio CDN1: Servidor web basado en NGINX
  cdn1:
    build:
      context: ./servers
      dockerfile: dockerfile
      args:
        - TEMPLATE_FILE=./cdn/nginx.conf.template
    container_name: cdn1  # ✅ Nombre fijo del contenedor
    environment:
      - NGINX_TRANSCODER1=${NGINX_IP_ADDRESS_TRANSCODER1}  # transcoder1
      - NGINX_TRANSCODER2=${NGINX_IP_ADDRESS_TRANSCODER2}  # transcoder2
    volumes:
      - ./servers/cdn/nginx_cache:/var/cache/nginx
      - ./servers/cdn/index.html:/nginx-1.26.3/html/index.html
    networks:
      - lan
    restart: always
    depends_on:
      - transcoder1
      - transcoder2
    ports:
      - "8082:80"

  # Servicio Transcoder1: Servidor de transcodificación
  transcoder1:
    build:
      context: ./servers
      dockerfile: dockerfile
      args:
        - TEMPLATE_FILE=./transcoderServers/transcoder1/nginx.conf.template
    container_name: transcoder1  # ✅ Nombre fijo del contenedor
    environment:
      - NGINX_MINIO_SERVER=${IP_ADDRESS_MINIO}:${MINIO_PORT}  # minio:9000
      - NGINX_MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - NGINX_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - NGINX_REGION=${MINIO_REGION}
      - NGINX_MINIO_BUCKET=${MINIO_BUCKET}
      - NGINX_MINIO_VIDEO_DIR=${MINIO_VIDEO_DIR}
      - NGINX_MINIO_COVERS_DIR=${MINIO_COVERS_DIR}
    volumes:
      - ./servers/transcoderServers/transcoder1/nginx_cache:/var/cache/nginx
      - ./servers/transcoderServers/transcoder1/index.html:/nginx-1.26.3/html/index.html
    networks:
      - lan
    restart: always
    depends_on:
      - minio

  # Servicio Transcoder2: Servidor de transcodificación
  transcoder2:
    build:
      context: ./servers
      dockerfile: dockerfile
      args:
        - TEMPLATE_FILE=./transcoderServers/transcoder2/nginx.conf.template
    container_name: transcoder2  # ✅ Nombre fijo del contenedor
    environment:
      - NGINX_MINIO_SERVER=${IP_ADDRESS_MINIO}:${MINIO_PORT}  # minio:9000
      - NGINX_MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - NGINX_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - NGINX_REGION=${MINIO_REGION}
      - NGINX_MINIO_BUCKET=${MINIO_BUCKET}
      - NGINX_MINIO_VIDEO_DIR=${MINIO_VIDEO_DIR}
      - NGINX_MINIO_COVERS_DIR=${MINIO_COVERS_DIR}
    volumes:
      - ./servers/transcoderServers/transcoder2/nginx_cache:/var/cache/nginx
      - ./servers/transcoderServers/transcoder2/index.html:/nginx-1.26.3/html/index.html
    networks:
      - lan
    restart: always
    depends_on:
      - minio

  # Servicio MinIO: Almacenamiento de objetos
  minio:
    image: quay.io/minio/minio
    container_name: minio  # ✅ Nombre fijo del contenedor
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_REGION=${MINIO_REGION}
    volumes:
      - ./servers/minio/aws3DataMinio:/data
    networks:
      - lan
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_PANEL_PORT}:9001"
    restart: always

  # Inicializador de MinIO
  minio-init:
    image: alpine:latest
    container_name: minio-init
    depends_on:
      - minio
    environment:
      - MINIO_HOST=${IP_ADDRESS_MINIO}  # minio
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
    volumes:
      - ./servers/minio/init-minio.sh:/init-minio.sh
    entrypoint: ["/bin/sh", "/init-minio.sh"]
    networks:
      - lan

  # Servicio PostgreSQL
  postgres:
    build: ./servers/postgresQl
    container_name: postgres  # ✅ Nombre fijo del contenedor
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=America/Mexico_City
    volumes:
      - ./servers/postgresQl/postgres_data:/var/lib/postgresql/data
      - ./servers/postgresQl/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lan
    ports:
      - "${DB_PORT}:5432"
    restart: always

  # Servicio pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin  # ✅ Nombre fijo del contenedor
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    networks:
      - lan
    ports:
      - "${PG_PORT}:80"
    restart: always
    depends_on:
      - postgres

  # 🎨 FRONTEND VITE - SERVICIO PRINCIPAL
  # ==========================================
  frontend:
    build:
      context: ./frontend/app
      dockerfile: dockerfile.frontend
      args:
        - NODE_ENV=development
        - SERVICE_TYPE=frontend
    container_name: front
    environment:
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_FRONT_URL_LOCAL=${VITE_FRONT_URL_LOCAL}
      - VITE_MODE=${VITE_MODE}
      - VITE_HOST_LOCAL=${VITE_HOST_LOCAL}
      - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    restart: unless-stopped
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

  # ==========================================
  # 📚 STORYBOOK - SERVICIO INDEPENDIENTE
  # ==========================================
  storybook:
    build:
      context: ./frontend/app
      dockerfile: dockerfile.storybook
      args:
        - NODE_ENV=development
        - SERVICE_TYPE=storybook
    container_name: storybook
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - STORYBOOK_DISABLE_TELEMETRY=true
      - STORYBOOK_DISABLE_UPDATES=true
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
      - /app/storybook-static
    ports:
      - "6006:6006"   
    restart: "no"

  # Servicio Backend Node.js
  backend:
    build:
      context: ./backend/app
      dockerfile: dockerfile.appdev  # ✅ Nombre correcto del dockerfile
    container_name: back  # ✅ Nombre fijo del contenedor
    environment:
      - IP_ADDRESS_POSTGRESQL=postgres # ✅ Usar nombre de servicio
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - IP_ADDRESS_MINIO=minio # ✅ Usar nombre de servicio
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${IP_ADDRESS_POSTGRESQL}  # postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_ENDPOINT=${IP_ADDRESS_MINIO}  # minio
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_VIDEO_DIR=${MINIO_VIDEO_DIR}
      - MINIO_COVERS_DIR=${MINIO_COVERS_DIR}
      - TEMP_PROCESSING_DIR=${TEMP_PROCESSING_DIR}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - EMAIL=${EMAIL}
      - PASS_EMAIL=${PASS_EMAIL}
      - BACK_PORT=${BACK_PORT}
      - FRONT_URL_LOCAL=${FRONT_URL_LOCAL}
      - WHITE_LIST=${WHITE_LIST}
    volumes:
      - ./backend/app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - lan
    ports:
      - "${BACK_PORT}:3000"
    restart: always
    depends_on:
      - postgres
      - minio

# Red Docker simple - sin IPs estáticas
networks:
  lan:
    driver: bridge