# Etapa única para desarrollo
FROM node:18-alpine

WORKDIR /usr/src/app

# Instala dependencias y nodemon global
COPY package*.json ./
RUN npm ci && npm install -g nodemon

# No copiamos código aquí porque lo montaremos como volumen
EXPOSE 3000

# Escucha cambios en todo el proyecto
CMD ["nodemon", "--watch", ".", "index.js"]
