# Etapa única para desarrollo
FROM node

WORKDIR /usr/src/app

#RUN apk add --no-cache ffmpeg

RUN apt-get update && apt-get install -y ffmpeg


# Instala dependencias y nodemon global
COPY package*.json ./
RUN npm install -g nodemon

# No copiamos código aquí porque lo montaremos como volumen
EXPOSE 3000

# Escucha cambios en todo el proyecto
CMD ["nodemon", "--watch", ".", "index.js"]
